### ISSUE TITLE
[feature Requests]: Add icons of shade and desk  for Breeze

### ISSUE THREAD

**Issue by ffs-akl** [labwc/labwc-artwork#24]
It's hard to find svg icons of shade and desk for the breeze theme.  Could someone make the breeze theme for labwc perfect?

**Comment by 01micko** [comment]
See if I can do it over the week end.

**Comment by ffs-akl** [comment]
Thank you very much!

**Comment by 01micko** [comment]
@knm100 about to push to close this, hope it's fine for you. :)

**Comment by ffs-akl** [comment]
well done, thank you !
